### ISSUE TITLE
Denim Dealers - T&C landingpage

### ISSUE THREAD

**Issue by gitte-cort** [jackjonesfashion/tasks#174]
Hi jeppe,

Please prepare a T& C landing page for the denim dealer campaign. You should have all you need.

**Comment by jeppeolesen** [comment]
Copy:

JACK & JONES COMPETITION: SHOW ‘EM HOW TO DO THE DENIM!

TERMS AND CONDITIONS
This competition is held by JACK & JONES, BESTSELLER A/S (“JACK & JONES”), Fredskovvej, 7330 Brande, Denmark. By entering the competition you accept and agree to comply with these terms and conditions. This competition is in no way sponsored or affiliated with Instagram. 

The competition runs from 20 July 2015 until 13 September 2015, and is open to people over the age of 18. The competition is not open to residents of Canada or Belarus.

You participate in the competition “Show ‘em how to do the denim!” by letting your local JACK & JONES shop assistant (“Denim Dealer”) style you. Once you are styled take a picture with you and your Denim Dealer. Upload the picture to Instagram, geotag the JACK & JONES store you’re at and tag it #jjdenimdealer #nameofdenimdealer. 

Please note that it is not necessary to purchase any of the items that your denim dealer styles you in. 

The coolest denim outfit wins. 

JACK & JONES will pick a lucky winner each week for 8 weeks. At the end of each week JACK & JONES will choose one winner and will inform the winner. 

You can participate all 8 weeks by uploading a new picture every week.  

PRIZE
The prize consists of a € 500 voucher and an out-of-hours shopping experience with a personal stylist so that each winner can get styled from head to toe in a new JACK & JONES denim outfit. 

No cash or credit alternatives are available and the prize is not transferable. 

The prize is subject to available styles and sizes at the JACK & JONES store.

  
RIGHTS TO AND USE OF THE UPLOADED PHOTO
Participants of the competition grant JACK & JONES a commercial, non-exclusive, worldwide and royalty free license to use the photos submitted in connection to this competition for marketing purposes on the JACK & JONES website and pages on social media (Facebook, Instagram, Twitter and Pinterest) as well as a right to edit the photos with graphic effects and layers. This license is valid for a period of six months, starting from the date of the first public use.  

By uploading your photo you certify that you have all rights to the uploaded photo, including all intellectual property rights, and that the photo does not infringe any third-party rights or is in any way illegal, offensive, abusive or defamatory. Furthermore, you certify that any person depicted in the uploaded photo has consented in writing to your submission of the photo. Furthermore, you accept to be liable for any claims based on deficiencies or non-existence of any rights to the uploaded photograph.

JACK & JONES reserves the right to request that Instagram removes photos that are offensive, abusive or do not comply with these terms and conditions. 

CONTACTING AND PUBLISHING THE WINNERS
The winners will be contacted using the “Direct” feature on Instagram, and later by the JACK & JONES store in order to schedule the out-of-hours shopping experience. 

If you follow the official JACK & JONES Instagram account, our message to you will appear immediately. However, if you are not following our page you will receive a request, which you must view in order to read our message. In case the winner does not respond within 7 days from the date of our first message, we reserve the right to pick a new winner. 

The winners will be announced on Facebook and Instagram. 

USE OF PERSONAL INFORMATION
JACK & JONES may use all photos submitted in connection to this competition for marketing purposes, as further explained in the above paragraph “Rights and use of the uploaded photos”.  

Furthermore, JACK & JONES may contact participants for the purpose of examining the possibility for entering into cooperation with participants, for example by offering them an opportunity to become JACK & JONES ambassadors. 

All winners are required to inform JACK & JONES of their full name, ages, address, phone number and e-mail. This information will be used in order to present the winners with the prize, and will be permanently deleted when the competition has ended. 

The announcement on Facebook and Instagram will appear for a longer period of time.

LAW AND VENUE 
The laws of Denmark, excluding conflict of law regulations, shall govern this competition as well as these terms and conditions. The court in Aarhus, Denmark shall settle any and all disputes arising from the competition or terms and conditions.

TAX
The price can be subject to personal or price tax depending on local tax regulation.

**Comment by jeppeolesen** [comment]
@gitte-cort Please figure out a way to communicate this in the highlights section of the site.

We'll need a CTA and possibly translations of the CTA, unless it's really generic like "Jeans Guide".

**Comment by gitte-cort** [comment]
It should just be “Denim Dealer Competition” and we don’t need it translated.

Gitte Cort Hansen
E-commerce Traffic   /   Social Media Responsible
P

+4599424773

M

+4552154773

E

gitte.hansen@bestseller.com<mailto:gitte.hansen@bestseller.com>

W

BESTSELLER.COM<http://bestseller.com>

BESTSELLER A/S
FREDSKOVVEJ 1, 7330 BRANDE
DENMARK
[cid:image001.png@01D0C2FE.7B5368D0]

**Comment by jeppeolesen** [comment]
![dd_t c image](https://cloud.githubusercontent.com/assets/1243023/8776578/8c891662-2ef2-11e5-8e31-de0887dad366.png)

**Comment by jeppeolesen** [comment]
@gitte-cort When will the link in the highlights need to go offline again?

**Comment by gitte-cort** [comment]
It will need to be under ”Diverse” and not “Highlights” and it will need to go offline 21. September.
[cid:image001.png@01D0C304.702590E0]

**Comment by jeppeolesen** [comment]
@gitte-cort In that case you'll need to ask Trine to create a category under "Diverse" that redirects to the **jj-denim-dealers-tcs** content asset, which is timed to be online until 21/9

You can preview the page here: http://dws.jackjones.se/Denim-Dealers---Terms-Conditions/jj-denim-dealers-tcs,sv_SE,pg.html
