### ISSUE TITLE
Storefront - Brand boxes overlapping selling points bar if no heroes are displayed

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#88]
Yes, there should always be a hero. 
Sometimes there isn't one, though, due to delayed replications / bugs etc.
Lets ensure the page doesn't look like this when that problem occurs.

![image](https://cloud.githubusercontent.com/assets/2851890/7291854/ebb9636e-e995-11e4-9a43-e160916ef1b8.png)

**Comment by jeppeolesen** [comment]
This is a consequence of both the highlights and brands having to overlap the hero. Fixing this would mean adding an extra check to the initialization of the entire page, that I would rather not add.

Instead I suggest adding generic JJ heroes that the site will default to if there's a gap in between timings or a replication doesn't go though. They should be easy enough to create, since we have categories like bestsellers and sale that we continuously use anyway.
